version: '3.8'

services:
  app:
    env_file: .env
    image: gestion_recette_api
    container_name: gestion_api
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql
    env_file: .env
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
